content:
  - name: news
    label: Posts
    path: content/news
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: content, label: Content, type: rich-text }